// Generated by diesel_ext
use chrono::offset::Utc;
use chrono::DateTime;
use diesel::{
    prelude::{AsChangeset, Associations, Identifiable, Insertable},
    Queryable, Selectable,
};
#[derive(
    Queryable, Debug, Selectable, AsChangeset, Insertable, Identifiable, Associations, PartialEq,
)]
#[diesel(belongs_to(Cart))]
#[diesel(check_for_backend(diesel::pg::Pg))]
#[diesel(table_name = crate::schema::cart_lines)]
pub struct CartLine {
    #[diesel(skip_insertion)]
    pub id: i32,
    pub cart_id: i32,
    pub product_id: i32,
    pub qty: i32,
    #[diesel(skip_insertion)]
    #[diesel(deserialize_as = DateTime<Utc>)]
    pub created_at: Option<DateTime<Utc>>,
    #[diesel(skip_insertion)]
    #[diesel(deserialize_as = DateTime<Utc>)]
    pub updated_at: Option<DateTime<Utc>>,
}

#[derive(Queryable, Debug, Selectable, AsChangeset, Insertable, Identifiable, PartialEq)]
#[diesel(check_for_backend(diesel::pg::Pg))]
#[diesel(table_name = crate::schema::carts)]
pub struct Cart {
    #[diesel(skip_insertion)]
    pub id: i32,
    pub user_id: i32,
    #[diesel(skip_insertion)]
    pub user_cart_id: i32,
    pub discount_id: Option<i32>,
}
